import assert from 'node:assert/strict';
import {mkdtemp, rm, access} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawn,execFileSync} from 'node:child_process';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const storage=await mkdtemp(join(tmpdir(),'nyumba-feedback-'));
const database=join(storage,'bookings.sqlite');
const origin='http://127.0.0.1:8095';
const env={...process.env,BOOKING_DB:database,BOOKING_SESSION_PATH:storage,BOOKING_EMAIL_ENABLED:'0',FEEDBACK_EMAIL_ENABLED:'1',BOOKING_SITE_URL:'https://visits.example.com'};
const server=spawn('php',['-S','127.0.0.1:8095','-t','public'],{env,stdio:'ignore'});
const worker=(when,mode='',extra={})=>JSON.parse(execFileSync('php',['tests/helpers/feedback-worker.php',database,String(Date.parse(when)/1000),mode],{env:{...env,...extra},encoding:'utf8'}));
let browser;
try {
 for(let i=0;i<50;i++){try{if((await fetch(origin)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({executablePath:process.env.UI_BROWSER_PATH});
 const combined=await access('src/views/v1.php').then(()=>true,()=>false);
 const page=await browser.newPage();
 await page.goto(origin+(combined?'/v1':'/')+'?book=feeding');
 await page.locator('#full-name').fill('Feedback Visitor');
 await page.locator('#email').fill('visitor@example.com');
 await page.locator('#phone').fill('0712345678');
 await page.locator('#visit-date').fill('2099-05-01');
 await page.locator('#time-slot').selectOption('11:00');
 await page.locator('#attendees').fill('1');
 await page.locator('[type=submit]').click();
 await page.waitForURL(/confirmation=1/);
 assert.equal(worker('2099-05-02T05:59:59Z').messages.length,0);
 const sent=worker('2099-05-02T06:00:00Z').messages;
 assert.equal(sent.length,1,'next-morning feedback invitation');
 assert.deepEqual(sent[0].payload.to,['visitor@example.com']);
 const link=sent[0].payload.text.match(/https:\/\/visits\.example\.com\/\S+/)[0];
 const url=link.replace('https://visits.example.com',origin);
 await page.goto(url);
 const blocked=await page.request.post(url,{form:{csrf:'wrong',attendance:'attended',rating:'5'}});
 assert.equal(blocked.status(),403);
 await page.reload();
 const csrf=await page.locator('[name=csrf]').inputValue();
 const invalid=await page.request.post(url,{form:{csrf,attendance:'attended',rating:'6',comments:'x'.repeat(2001)}});
 assert.equal(invalid.status(),422);
 assert.match(await invalid.text(),/2,000 characters/);
 await page.reload();
 await page.getByLabel('I attended').check();
 await page.getByLabel('5 stars', {exact:true}).check();
 await page.getByLabel('What did you enjoy?').fill('A wonderful visit.');
 await page.getByRole('button',{name:'Send feedback',exact:true}).click();
 await page.getByRole('heading',{name:'Thank you for your feedback.'}).waitFor();
 await page.goto(url);
 assert.equal(await page.locator('form').count(),0);
 assert.equal(worker('2099-05-03T06:00:00Z').messages.length,0);
 // An overnight invitation must wait until the morning after departure.
 await page.goto(origin+(combined?'/v2':'/')+'?book=galana');
 await page.locator('#full-name').fill('Overnight Feedback');
 await page.locator('#email').fill('overnight@example.com');
 await page.locator('#phone').fill('0712345678');
 await page.locator('#visit-date').fill('2099-12-30');
 await page.locator('#time-slot').selectOption('11:00');
 await page.locator('#attendees').fill('2');
 await page.locator('#overnight').check();
 await page.locator('#departure-date').fill('2100-01-02');
 await page.locator('#overnight-guests').fill('2');
 await page.locator('[type=submit]').click();
 await page.waitForURL(/confirmation=1/);
 assert.equal(worker('2100-01-03T05:59:59Z').messages.length,0);
 const overnight=worker('2100-01-03T06:00:00Z').messages;
 assert.equal(overnight.length,1,'invitation after overnight departure');
 assert.match(overnight[0].payload.text,/2099-12-30.*2100-01-02/);
 const overnightUrl=overnight[0].payload.text.match(/https:\/\/visits\.example\.com\/\S+/)[0].replace('https://visits.example.com',origin);
 const native=await browser.newContext({javaScriptEnabled:false});
 const nativePage=await native.newPage();
 await nativePage.goto(overnightUrl);
 await nativePage.getByLabel('I didn’t attend').check();
 await nativePage.getByRole('button',{name:'Send feedback',exact:true}).click();
 await nativePage.getByRole('heading',{name:'Thank you for your feedback.'}).waitFor();
 await native.close();
 console.log('PASS overnight year boundary and non-attendance without JavaScript');
 // Recovery path: pause, timeout, retry with the same payload, then stop at expiry.
 async function bookDay(email) {
  await page.goto(origin+(combined?'/v3':'/')+'?book=sahajanand');
  await page.locator('#full-name').fill('Retry Feedback'); await page.locator('#email').fill(email);
  await page.locator('#phone').fill('0712345678'); await page.locator('#visit-date').fill('2100-05-01');
  await page.locator('#time-slot').selectOption('11:00'); await page.locator('#attendees').fill('1');
  await page.locator('[type=submit]').click(); await page.waitForURL(/confirmation=1/);
 }
 await bookDay('retry@example.com');
 assert.equal(worker('2100-05-02T06:00:00Z','',{FEEDBACK_EMAIL_ENABLED:'0'}).messages.length,0);
 const failed=worker('2100-05-02T07:00:00Z','fail');
 assert.equal(failed.result.retry,1);
 assert.equal(worker('2100-05-02T07:00:59Z').messages.length,0);
 const retry=worker('2100-05-02T07:01:00Z');
 assert.deepEqual(retry.messages,failed.messages,'immutable feedback retry');
 const retryUrl=retry.messages[0].payload.text.match(/https:\/\/visits\.example\.com\/\S+/)[0].replace('https://visits.example.com',origin);
 await page.goto(retryUrl);
 // A scanner GET does not consume the invitation.
 await page.reload(); assert.equal(await page.locator('form').count(),1);
 await page.getByLabel('I attended').check();
 await page.getByRole('button',{name:'Send feedback',exact:true}).click();
 assert.match(await page.locator('.error-summary').innerText(),/rating from 1 to 5/);
 await page.getByLabel('What did you enjoy?').fill('<script>alert(1)</script>');
 await page.getByLabel('I didn’t attend').check();
 await page.getByRole('button',{name:'Send feedback',exact:true}).click();
 await page.getByRole('heading',{name:'Thank you for your feedback.'}).waitFor();
 assert.equal((await page.goto(origin+'/v1/feedback?token='+ '0'.repeat(64))).status(),404);
 await bookDay('review@example.com');
 assert.equal(worker('2100-05-02T08:00:00Z','fail').result.retry,1);
 const expired=worker('2100-05-03T07:00:00Z');
 assert.equal(expired.result.review,1); assert.equal(expired.messages.length,0);
 console.log('PASS feedback pause, catch-up, retries, expiry, validation and scanner-safe links');
 console.log('PASS day booking → due email → private form → saved response, without duplicate sends');
} finally {await browser?.close();server.kill();await rm(storage,{recursive:true,force:true});}
