<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nyumba · Administration</title>
<link rel="icon" href="/assets/nyumba-group.svg" type="image/svg+xml">
<style>
*{box-sizing:border-box}body{margin:0;background:#f5f4ed;color:#173d33;font:16px/1.5 system-ui,sans-serif}header,main{max-width:1150px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #ccd5ca}h1{overflow-wrap:anywhere;font-size:clamp(28px,5vw,42px);letter-spacing:-.04em}a{color:#205c43}button{background:#205c43;color:white;border:0;border-radius:6px;padding:12px 20px;font:inherit;cursor:pointer}input,select{font:inherit;padding:10px;border:1px solid #879b8c;border-radius:5px;width:100%;background:white}label{display:block;margin:16px 0}a:focus-visible,button:focus-visible{outline:2px solid #205c43;outline-offset:2px}input:focus,select:focus{border-color:#205c43;outline:1px solid #205c43;outline-offset:0}.login{max-width:420px;margin:48px auto}.error{padding:14px;background:#ffe5d9;color:#74280b}.table{overflow:auto;background:white;border:1px solid #d5ddcf;border-radius:8px}table{border-collapse:collapse;width:100%;text-align:left}th,td{padding:15px;border-bottom:1px solid #e5e8df;white-space:nowrap}th{font-size:13px;text-transform:uppercase;letter-spacing:.04em}nav{display:flex;gap:24px;margin:24px 0}.muted{color:#586e62}dl{display:grid;grid-template-columns:minmax(130px,1fr) 3fr;gap:12px}dd{margin:0;overflow-wrap:anywhere;white-space:pre-wrap}.filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;align-items:end;margin-bottom:24px}.filters label{margin:0}.panel{padding:24px;background:white;border:1px solid #d5ddcf;border-radius:8px;margin:24px 0}@media(max-width:550px){header,main{padding:16px}dl{grid-template-columns:1fr;gap:4px}dd{margin-bottom:12px}}
</style></head><body>
<header><strong>NYUMBA <span class="muted">/ Administration</span></strong><?php if ($authenticated): ?><form action="/admin/logout" method="post"><input type="hidden" name="csrf" value="<?=ae($_SESSION['csrf'])?>"><button>Sign out</button></form><?php endif; ?></header>
<main>
<?php if ($error): ?><p class="error" role="alert"><?=ae($error)?></p><?php endif; ?>
<?php if ($path === '/admin/login'): ?>
<section class="login"><h1>Welcome back.</h1><p class="muted">Sign in to review visits and visitor feedback.</p><form method="post" action="/admin/login"><input type="hidden" name="csrf" value="<?=ae($_SESSION['csrf'])?>"><label>Username<input name="username" autocomplete="username" required maxlength="200"></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button>Sign in</button></form></section>
<?php elseif ($booking): ?>
<a href="<?=ae(adminListUrl($filters,$page))?>">Back to bookings</a><h1>Booking <?=ae($booking['reference'])?></h1>
<section class="panel"><h2>Visit details</h2><dl>
<?php $fields = ['Visitor'=>$booking['full_name'], 'Phone'=>$booking['phone'], 'Email'=>$booking['email'] ?: 'Not provided', 'Destination'=>$destinations[$booking['destination']] ?? $booking['destination'], 'Visit date'=>date('j M Y',strtotime($booking['visit_date'])), 'Time'=>date('g:i A',strtotime($booking['booked_time'])), 'Guests'=>$booking['attendees'], 'Status'=>'Automatically confirmed', 'Created'=>adminTimestamp($booking['created_at'])];
if ($booking['overnight']) $fields += ['Arrival'=>date('j M Y',strtotime($booking['arrival_date'])), 'Departure'=>date('j M Y',strtotime($booking['departure_date'])), 'Overnight guests'=>$booking['overnight_guests']];
foreach($fields as $label=>$value): ?><dt><?=ae($label)?></dt><dd><?=ae($value)?></dd><?php endforeach; ?></dl></section>
<section class="panel"><h2>Visitor feedback</h2><?php if (!$booking['attendance']): ?><p>No feedback received.</p><?php else: ?><dl><dt>Self-reported attendance</dt><dd><?=$booking['attendance']==='attended'?'Attended':'Did not attend'?></dd><?php if($booking['attendance']==='attended'): ?><dt>Rating</dt><dd><?=ae($booking['rating'])?> / 5</dd><?php endif; ?>
<?php foreach(['enjoyment'=>'What they enjoyed','improvement'=>'Suggested improvements','comments'=>'Comments'] as $key=>$label): ?><dt><?=ae($label)?></dt><dd><?=ae($booking[$key] ?: 'Not provided')?></dd><?php endforeach; ?><dt>Submitted</dt><dd><?=ae(adminTimestamp($booking['submitted_at']))?></dd></dl><?php endif; ?></section>
<?php else: ?>
<h1>Bookings</h1><p class="muted">Visit records · Read-only</p>
<form class="filters" method="get" action="/admin"><label>Search reference or name<input name="q" maxlength="200" value="<?=ae($filters['q'])?>"></label><label>Destination<select name="destination" aria-label="Destination"><option value="">All destinations</option><?php foreach($destinations as $key=>$name): ?><option value="<?=ae($key)?>" <?=$filters['destination']===$key?'selected':''?>><?=ae($name)?></option><?php endforeach; ?></select></label><label>From date<input type="date" name="from" value="<?=ae($filters['from'])?>"></label><label>To date<input type="date" name="to" value="<?=ae($filters['to'])?>"></label><button>Apply filters</button><a href="/admin">Clear filters</a></form>
<?php if (!$rows): ?><p>No bookings found.</p><?php else: ?>
<div class="table" tabindex="0" role="region" aria-label="Bookings"><table><thead><tr><th>Reference</th><th>Visitor</th><th>Destination</th><th>Visit date</th><th>Time</th><th>Guests</th><th>Feedback</th></tr></thead><tbody>
<?php foreach (array_slice($rows,0,25) as $row): ?><tr><td><a href="<?=ae('/admin/bookings/'.$row['id'].'?'.http_build_query($filters + ['page'=>$page]))?>"><?=ae($row['reference'])?></a></td><td><?=ae($row['full_name'])?></td><td><?=ae($destinations[$row['destination']] ?? $row['destination'])?></td><td><?=ae(date('j M Y', strtotime($row['visit_date'])))?></td><td><?=ae(date('g:i A', strtotime($row['booked_time'])))?></td><td><?=ae($row['attendees'])?></td><td><?=$row['has_feedback']?'Received':'Awaiting response'?></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?>
<nav aria-label="Pagination"><?php if ($page>1): ?><a href="<?=ae(adminListUrl($filters,$page-1))?>">Previous</a><?php endif; ?><span>Page <?=$page?></span><?php if(count($rows)>25): ?><a href="<?=ae(adminListUrl($filters,$page+1))?>">Next</a><?php endif; ?></nav>
<?php endif; ?></main></body></html>
