<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=ae($title)?> · Nyumba admin</title><link rel="stylesheet" href="/assets/admin/workspace.css"><link rel="stylesheet" href="/assets/community.css"></head><body>
<header><a class="brand" href="/admin"><img src="/assets/nyumba-group.svg" alt="Nyumba Group" width="42" height="55"><span>NYUMBA GROUP<small>Administration</small></span></a><form action="/admin/logout" method="post"><input type="hidden" name="csrf" value="<?=ae($_SESSION['csrf'])?>"><button>Sign out</button></form></header>
<main><nav class="workspace-nav" aria-label="Administration"><a href="/admin">Bookings</a><a href="/admin/school-requests">School requests</a><a href="/admin/donations">Donations</a></nav><h1><?=ae($title)?></h1><?php if($kind==='donations'): ?><nav class="workspace-nav" aria-label="Donation records"><a href="/admin/donations">Transactions</a><a href="/admin/donations/attempts">Payment attempts</a></nav><p class="muted">Dates filter <?=isset($isAttempt)&&$isAttempt?'attempt creation':'transaction time'?> in Kenya local time. Sandbox records never count toward production totals.</p><?php endif; ?>
<?php if($detail): ?><p><a href="<?=ae($base.'?'.http_build_query($f+['page'=>$page]))?>">Back to <?=ae(strtolower($title))?></a></p><?php if($kind==='school-requests'): require __DIR__.'/school-admin-detail.php'; else: ?><section class="panel"><dl><?php foreach($detailFields as $label=>$value): ?><dt><?=ae($label)?></dt><dd class="community-history"><?=ae($value??'Not provided')?></dd><?php endforeach; ?></dl></section><?php endif; ?>
<?php if(isset($receiptSearch)): ?><p><a href="<?=ae('/admin/donations?q='.urlencode($receiptSearch))?>">View matching receipts</a></p><?php endif; ?>
<?php if($history): ?><h2>Processing history</h2><ul><?php foreach($history as $event): ?><li class="community-history"><?=ae($event)?></li><?php endforeach; ?></ul><?php endif; ?>
<?php else: ?>
<?php if(isset($totals)): ?><p class="donation-total">Verified donations (production): <?=ae($totals['count'])?> · Net total: KES <?=ae(number_format($totals['amount']/100,2))?></p><?php endif; ?>
<form class="filters" method="get" action="<?=ae($base)?>"><label><?=$kind==='school-requests'?'Search reference or name':'Search receipt or account reference'?><input name="q" maxlength="200" value="<?=ae($f['q'])?>"></label><label><?=$kind==='school-requests'?'Support type':'State'?><select name="state"><option value="">All</option><?php foreach($states as $key=>$label): ?><option value="<?=ae($key)?>" <?=$f['state']===$key?'selected':''?>><?=ae($label)?></option><?php endforeach; ?></select></label><label>From date<input type="date" name="from" value="<?=ae($f['from'])?>"></label><label>To date<input type="date" name="to" value="<?=ae($f['to'])?>"></label><button>Apply filters</button><a href="<?=ae($base)?>">Clear filters</a></form>
<?php if(!$rows): ?><p>No records found.</p><?php else: ?><div class="table community-table" role="region" aria-label="<?=ae($title)?>"><table><thead><tr><?php foreach(array_keys($rows[0])as $key):if($key==='id')continue;?><th><?=ae($key)?></th><?php endforeach; ?></tr></thead><tbody><?php foreach($rows as $row): ?><tr><?php foreach($row as $key=>$value):if($key==='id')continue;?><td data-label="<?=ae($key)?>"><?php if($key==='Reference'): ?><a href="<?=ae($base.'/'.$row['id'].'?'.http_build_query($f+['page'=>$page]))?>"><?=ae($value)?></a><?php else: ?><?=ae($value)?><?php endif; ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<nav aria-label="Pagination"><?php if($page>1): ?><a href="<?=ae($base.'?'.http_build_query($f+['page'=>$page-1]))?>">Previous</a><?php endif; ?><span>Page <?=$page?></span><?php if($hasNext): ?><a href="<?=ae($base.'?'.http_build_query($f+['page'=>$page+1]))?>">Next</a><?php endif; ?></nav>
<?php endif; ?></main></body></html>
